// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet
// From decision table
// "/data/github/asciidoctorj-liquibase-extension/src/main/resources/LiquibaseParseChangelogFile.lfet"
// 27.10.2019 22:22
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.1.5 (190905b) build in default

package org.uniqueck.asciidoctorj.liquibase.parser.lfet;

public final class LiquibaseParseChangelogFileRules
{
    public final void execute(ILiquibaseParseChangelogFile iface)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=org.uniqueck.asciidoctorj.liquibase.parser.lfet
        // $$InterfaceTraceAfterRule=true
        // $$InterfaceRuleGroups = true
        // $$InterfaceName=ILiquibaseParseChangelogFile
        // $$InterfaceRulesClassname=LiquibaseParseChangelogFileRules
        // Prolog Decision Table <----
        
        if ( iface.isElementEqualCreateTable() )
        {
            // Rule R01 ---->
            
            iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 1);
            iface.doExtractTable();
            
            iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 1);
            
            // Rule R01 <----
        }
        else
        {
            if ( iface.isElementEqualInclude() )
            {
                // Rule R02 ---->
                
                iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 2);
                iface.doFollowInclude();
                
                iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 2);
                
                // Rule R02 <----
            }
            else
            {
                if ( iface.isElementEqualChangeSet() )
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 3);
                    iface.doParseChangeSet();
                    
                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 3);
                    
                    // Rule R03 <----
                }
                else
                {
                    if ( iface.isElementEqualAddPrimaryKey() )
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 4);
                        iface.doSetPrimaryKeyForColumn();
                        
                        iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 4);
                        
                        // Rule R04 <----
                    }
                    else
                    {
                        if ( iface.isElementEqualDropTable() )
                        {
                            // Rule R05 ---->
                            
                            iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 5);
                            iface.doDropTable();
                            
                            iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 5);
                            
                            // Rule R05 <----
                        }
                        else
                        {
                            if ( iface.isElementEqualPreConditions() )
                            {
                                // Rule R06 ---->
                                
                                iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 6);
                                iface.doIgnoreElement();
                                
                                iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 6);
                                
                                // Rule R06 <----
                            }
                            else
                            {
                                if ( iface.isElementEqualSql() )
                                {
                                    // Rule R07 ---->
                                    
                                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 7);
                                    iface.doIgnoreElement();
                                    
                                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 7);
                                    
                                    // Rule R07 <----
                                }
                                else
                                {
                                    if ( iface.isElementEqualCreateSequence() )
                                    {
                                        // Rule R08 ---->
                                        
                                        iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 8);
                                        iface.doIgnoreElement();
                                        
                                        iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 8);
                                        
                                        // Rule R08 <----
                                    }
                                    else
                                    {
                                        if ( iface.isElementEqualCreateProcedure() )
                                        {
                                            // Rule R09 ---->
                                            
                                            iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 9);
                                            iface.doIgnoreElement();
                                            
                                            iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 9);
                                            
                                            // Rule R09 <----
                                        }
                                        else
                                        {
                                            if ( iface.isElementEqualRenameColumn() )
                                            {
                                                // Rule R10 ---->
                                                
                                                iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 10);
                                                iface.doRenameColumn();
                                                
                                                iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 10);
                                                
                                                // Rule R10 <----
                                            }
                                            else
                                            {
                                                if ( iface.isElementEqualComment() )
                                                {
                                                    // Rule R11 ---->
                                                    
                                                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 11);
                                                    iface.doIgnoreElement();
                                                    
                                                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 11);
                                                    
                                                    // Rule R11 <----
                                                }
                                                else
                                                {
                                                    if ( iface.isElementEqualAddColumn() )
                                                    {
                                                        // Rule R12 ---->
                                                        
                                                        iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 12);
                                                        iface.doAddColumn();
                                                        
                                                        iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 12);
                                                        
                                                        // Rule R12 <----
                                                    }
                                                    else
                                                    {
                                                        if ( iface.isElementEqualDropColumn() )
                                                        {
                                                            // Rule R13 ---->
                                                            
                                                            iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 13);
                                                            iface.doDropColumn();
                                                            
                                                            iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 13);
                                                            
                                                            // Rule R13 <----
                                                        }
                                                        else
                                                        {
                                                            if ( iface.isElementEqualRollback() )
                                                            {
                                                                // Rule R14 ---->
                                                                
                                                                iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 14);
                                                                iface.doIgnoreElement();
                                                                
                                                                iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 14);
                                                                
                                                                // Rule R14 <----
                                                            }
                                                            else
                                                            {
                                                                if ( iface.isElementEqualDropSequence() )
                                                                {
                                                                    // Rule R15 ---->
                                                                    
                                                                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 15);
                                                                    iface.doIgnoreElement();
                                                                    
                                                                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 15);
                                                                    
                                                                    // Rule R15 <----
                                                                }
                                                                else
                                                                {
                                                                    if ( iface.isElementEqualAddUniqueConstraint() )
                                                                    {
                                                                        // Rule R16 ---->
                                                                        
                                                                        iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 16);
                                                                        iface.doIgnoreElement();
                                                                        
                                                                        iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 16);
                                                                        
                                                                        // Rule R16 <----
                                                                    }
                                                                    else
                                                                    {
                                                                        if ( iface.isElementEqualAddForeignKeyConstraint() )
                                                                        {
                                                                            // Rule R17 ---->
                                                                            
                                                                            iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 17);
                                                                            iface.doAddForeignKeyConstraint();
                                                                            
                                                                            iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 17);
                                                                            
                                                                            // Rule R17 <----
                                                                        }
                                                                        else
                                                                        {
                                                                            if ( iface.isElementEqualTagDatabase() )
                                                                            {
                                                                                if ( iface.isTagEqualTillTag() )
                                                                                {
                                                                                    // Rule R18 ---->
                                                                                    
                                                                                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 18);
                                                                                    iface.doFinishParsing();
                                                                                    
                                                                                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 18);
                                                                                    
                                                                                    // Rule R18 <----
                                                                                }
                                                                                else
                                                                                {
                                                                                    // Rule R19 ---->
                                                                                    
                                                                                    iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 19);
                                                                                    iface.doSkipTag();
                                                                                    
                                                                                    iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 19);
                                                                                    
                                                                                    // Rule R19 <----
                                                                                }
                                                                            }
                                                                            else
                                                                            {
                                                                                // Rule R20 ---->
                                                                                
                                                                                iface.doTrace("LiquibaseParseChangelogFile", "20191027.222244", 20, 20);
                                                                                iface.doLogUnsupportedElement();
                                                                                
                                                                                iface.doTraceAfterRule("LiquibaseParseChangelogFile", "20191027.222244", 20, 20);
                                                                                
                                                                                // Rule R20 <----
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.1.5 (190905b) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.1.5 (190905b), http://www.lohrfink.de/lfet

